### ISSUE TITLE
Add-on no longer compatible with version 68.2.0 

### ISSUE THREAD

**Issue by marcypooh-san** [ysard/mintrayr#46] opened 2019-10-31 13:51 UTC
I had an update of thunderbird today to 68.2.0 and it killed the compatibility with the add-on.

**To Reproduce**

**Expected behavior**
It should minimize to tray when minimized

**Environment 
 - OS: Windows 10
 - Thunderbird Version 68.2.0 
 - MinimizeToTray Reanimated Version 1.4.11

**Comment by Croydon** [comment] 2019-10-31 15:19
Duplicate of #43. Please close this one and use the search next time 😃

**Closed as completed** 2019-10-31 15:23 UTC
