### ISSUE TITLE
Add-on not compatible with last update v68.2.1

### ISSUE THREAD

**Issue by fsignoret** [ysard/mintrayr#47] opened 2019-11-02 14:50 UTC
When getting the last Thunderbird update, the add-on is not active anymore.

**To Reproduce**
Update Thunderbird to at least v68.2.1.
Thunderbird says "the extension is obsolete and not compatible".

**Expected behavior**
Closing thunderbird minimizes it to tray.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Thunderbird Version 68.2.1
 - MinimizeToTray Reanimated Version 1.4.11

**Comment by Croydon** [comment] 2019-11-02 17:41
Duplicate of #43. Please close this one and use the search next time 😃

(This is now the third duplicate issue)

**Closed as completed** 2019-11-02 18:20 UTC
