### ISSUE TITLE
No longer compatible to Thunderbird 68.2.0

### ISSUE THREAD

**Issue by doffine** [ysard/mintrayr#45] opened 2019-10-30 15:35 UTC
**Describe the bug**
Thunderbird 68.2.0 says the plugin is not compatible to Thunderbird 68.2.0 and disables it in the addons.

**To Reproduce**
Install the plugin in Thunderbird 68.2.0.

**Expected behavior**
It should work as usual.

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - Thunderbird Version 68.2.0
 - MinimizeToTray Reanimated Version 1.4.11

![not_compatible](https://user-images.githubusercontent.com/34769813/67873043-2853df80-fb33-11e9-9f2e-4dcc18cce8ee.jpg)

**Comment by Croydon** [comment] 2019-10-31 01:10
Duplicate of #43. Please close this one

**Closed as completed** 2019-10-31 12:45 UTC
